name: Build Powercuff Rootless

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    env:
      THEOS: ${{ github.workspace }}/theos

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean Ghost Submodules
        run: |
          # This forces Git to forget about that framework folder
          git rm -r --cached framework || true
          rm -rf .gitmodules || true

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $THEOS
          
      - name: Setup SDK
        run: |
          # Remove the existing empty sdks folder created by Theos install
          rm -rf $THEOS/sdks
          git clone https://github.com/theos/sdks.git $THEOS/sdks
          
      - name: Build Package
        run: |
          export THEOS_PACKAGE_SCHEME=rootless
          make package FINALPACKAGE=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Powercuff-Rootless-Deb
          path: packages/*.deb
